name: 'PR Action'
description: 'Testing PR'
inputs:
  worm-name:
    description: 'worm-name'
    required: true
    default: 'Hihoh'
runs:
  using: "composite"
  steps:
    - run: echo Hello, Worm ${{ inputs.who-to-greet }}!
      shell: bash
    - run: ${{ github.action_path }}/pr-action.sh
      shell: bash
