name: pr-opened
on:
  pull_request:
    branches:
      - master
    types: [opened]
jobs:
  pr-opened:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create-service-comment
        uses: ./.github/actions/create-service-comment
        with:
          auth-token: ${{ secrets.GITHUB_TOKEN }}
