name: pr-test
on: pull_request
jobs:
  create-service-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: create-service-comment
        name: create-service-comment
        uses: ./.github/actions/create-service-comment
        with:
          auth-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["E2E Status", "Build Link"]'
    if: ${{ github.event.action == 'opened' }}
  tests-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: pr-action
        name: pr-action
        uses: ./.github/actions/pr-action
        with:
          worm-name: Swadeek
      - name: update-service-comment-with-test-result
        uses: ./.github/actions/update-service-comment
        if: ${{ always() }}
        with:
          auth-token: ${{ secrets.GITHUB_TOKEN }}
          label: E2E Status
          value: ${{ steps.pr-action.outcome }}
        continue-on-error: true
